AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
FACEBOOK_ID:
FACEBOOK_SECRET:
development:
  SENDGRID_PASSWORD:
  SENDGRID_USERNAME:
  AWS_BUCKET:
  FACEBOOK_ID:
  FACEBOOK_SECRET:
  TWITTER_CONSUMER_KEY:
  TWITTER_CONSUMER_SECRET:
  MAILCHIMP_LIST_ID:
  MAILCHIMP_API_KEY:
production:
  AWS_BUCKET:
  FACEBOOK_ID:
  FACEBOOK_SECRET:
  TWITTER_CONSUMER_KEY:
  TWITTER_CONSUMER_SECRET:
  MAILCHIMP_LIST_ID:
  MAILCHIMP_API_KEY:
