AWS_ACCESS_KEY_ID:
AWS_SECRET_ACCESS_KEY:
FACEBOOK_ID:
FACEBOOK_SECRET:
development:
  SENDGRID_PASSWORD:
  SENDGRID_USERNAME:
  AWS_BUCKET:
  FACEBOOK_ID:
  FACEBOOK_SECRET:
production:
  AWS_BUCKET:
  FACEBOOK_ID:
  FACEBOOK_SECRET: